import "@/app/globals.css";
import { Inter } from 'next/font/google'

// Apps
// import {MetronicI18nProvider} from '../_metronic/i18n/Metronici18n'
import '../_metronic/assets/sass/style.react.scss'
import '../_metronic/assets/fonticon/fonticon.css'
import '../_metronic/assets/keenicons/duotone/style.css'
import '../_metronic/assets/keenicons/outline/style.css'
import '../_metronic/assets/keenicons/solid/style.css'
/**
 * TIP: Replace this style import with rtl styles to enable rtl mode
 *
 * import './_metronic/assets/css/style.rtl.css'
 **/
import '../_metronic/assets/sass/style.scss'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Payroll Login',
  description: 'Generated by create next app',
}

export default function DashboardLayout({ children }) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.className}`}>
        {children}
      </body>
    </html>
  )
}
