import "@/app/globals.css";
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Payroll Login',
  description: 'Generated by create next app',
}

export default function DashboardLayout({ children }) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.className}`}>
        {children}
      </body>
    </html>
  )
}
