import { Inter } from 'next/font/google'
import Header from '../../components/Header'
import Sidebar from '../../components/Sidebar'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Payroll Dashboard',
  description: 'Generated by create next app',
}

export default function DashboardLayout({ children }) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.className}`}>
        <Header />
        <div className="flex flex-col md:flex-row">
          {/* <Sidebar /> */}
          <main className="flex-1 p-4 min-h-screen">
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}
